name: Python Unit Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'services/compliance_service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.7"

      - name: Install dependencies
        working-directory: services/compliance_service
        run: |
            uv venv .venv
            source .venv/bin/activate
            uv pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        working-directory: services/compliance_service
        run: |
            source .venv/bin/activate
            uv run pytest --import-mode=importlib
            