name: Python Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.7"

      - name: Install dependencies
        run: |
            uv venv .venv
            source .venv/bin/activate
            uv sync --locked --all-extras --dev

      - name: Install OpenTelemetry dependencies
        run: uv pip install opentelemetry-distro opentelemetry-exporter-otlp

      - name: Install OpenTelemetry auto instrumentation
        run: uv run opentelemetry-bootstrap -a requirements | uv pip install --requirement -
          
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: |
            source .venv/bin/activate
            uv run pytest --import-mode=importlib
            