name: Python Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.7"

      - name: Install dependencies
        run: |
            uv venv .venv
            source .venv/bin/activate
            uv sync --locked --all-extras --dev

      - name: Run tests
        working-directory: 
            ${{ github.workspace }} 
        env: 
            PYTHONPATH: 
                ${{ github.workspace }}
        run: |
            source .venv/bin/activate
            uv run pytest tests
            